version: "3"
services:
  #
  # Webserver
  #
  webserver:
    image: von-network-base
    command: "bash -c './scripts/start_webserver.sh'"
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
      - GENESIS_URL=${GENESIS_URL}
      - ANONYMOUS=${ANONYMOUS}
      - LEDGER_SEED=${LEDGER_SEED}
      - LEDGER_CACHE_PATH=${LEDGER_CACHE_PATH}
      - MAX_FETCH=${MAX_FETCH:-50000}
      - RESYNC_TIME=${RESYNC_TIME:-120}
      - REGISTER_NEW_DIDS=${REGISTER_NEW_DIDS:-True}
      - LEDGER_INSTANCE_NAME=${LEDGER_INSTANCE_NAME:-localhost}
      - WEB_ANALYTICS_SCRIPT=${WEB_ANALYTICS_SCRIPT}
      - INFO_SITE_TEXT=${INFO_SITE_TEXT}
      - INFO_SITE_URL=${INFO_SITE_URL}
    networks:
      - von
    ports:
      - ${WEB_SERVER_HOST_PORT:-9000}:8000
    volumes:
      - ./config:/home/indy/config
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - webserver-ledger:/home/indy/ledger

  #
  # Nodes
  #
  nodes:
    image: von-network-base
    command: "bash -c './scripts/start_nodes.sh'"
    networks:
      - von
    ports:
      - 9701:9701
      - 9702:9702
      - 9703:9703
      - 9704:9704
      - 9705:9705
      - 9706:9706
      - 9707:9707
      - 9708:9708
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
    volumes:
      - nodes-data:/home/indy/ledger

  # node1:
  #   image: von-network-base
  #   command: "bash -c './scripts/start_node.sh 1'"
  #   networks:
  #     - von
  #   ports:
  #     - 9701:9701
  #     - 9702:9702
  #   environment:
  #     - IP=${IP}
  #     - IPS=${IPS}
  #     - DOCKERHOST=${DOCKERHOST}
  #     - LOG_LEVEL=${LOG_LEVEL}
  #     - RUST_LOG=${RUST_LOG}
  #   volumes:
  #     - node1-data:/home/indy/ledger
  # node2:
  #   image: von-network-base
  #   command: "bash -c './scripts/start_node.sh 2'"
  #   networks:
  #     - von
  #   ports:
  #     - 9703:9703
  #     - 9704:9704
  #   environment:
  #     - IP=${IP}
  #     - IPS=${IPS}
  #     - DOCKERHOST=${DOCKERHOST}
  #     - LOG_LEVEL=${LOG_LEVEL}
  #     - RUST_LOG=${RUST_LOG}
  #   volumes:
  #     - node2-data:/home/indy/ledger
  # node3:
  #   image: von-network-base
  #   command: "bash -c './scripts/start_node.sh 3'"
  #   networks:
  #     - von
  #   ports:
  #     - 9705:9705
  #     - 9706:9706
  #   environment:
  #     - IP=${IP}
  #     - IPS=${IPS}
  #     - DOCKERHOST=${DOCKERHOST}
  #     - LOG_LEVEL=${LOG_LEVEL}
  #     - RUST_LOG=${RUST_LOG}
  #   volumes:
  #     - node3-data:/home/indy/ledger
  # node4:
  #   image: von-network-base
  #   command: "bash -c './scripts/start_node.sh 4'"
  #   networks:
  #     - von
  #   ports:
  #     - 9707:9707
  #     - 9708:9708
  #   environment:
  #     - IP=${IP}
  #     - IPS=${IPS}
  #     - DOCKERHOST=${DOCKERHOST}
  #     - LOG_LEVEL=${LOG_LEVEL}
  #     - RUST_LOG=${RUST_LOG}
  #   volumes:
  #     - node4-data:/home/indy/ledger
  # alice_agent:
  #   image: bcgovimages/aries-cloudagent:py36-1.11-1_0.3.5
  #   environment:
  #     - LEDGER_URL=${LEDGER_URL}
  #     - WALLET_TYPE=${WALLET_TYPE}
  #     - WALLET_ENCRYPTION_KEY=${WALLET_ENCRYPTION_KEY}
  #     - INDY_WALLET_SEED=${INDY_WALLET_SEED}
  #     # - INDY_WALLET_DID=${INDY_WALLET_DID}
  #     - WEBHOOK_URL=${WEBHOOK_URL}/agentcb
  #     - HTTP_INTERFACE_PORT=${HTTP_INTERFACE_PORT}
  #     - WS_INTERFACE_PORT=${WS_INTERFACE_PORT}
  #     - AGENT_ADMIN_PORT=${AGENT_ADMIN_PORT}
  #     - AGENT_NAME=${AGENT_NAME}
  #   networks:
  #     - von
  #   ports:
  #     - 8030:8030
  #     - 8031:8031
  #   entrypoint: /bin/bash
  #   command: [
  #       "-c",
  #       "curl -d '{\"seed\":\"${INDY_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${AGENT_NAME}\"}' -X POST ${LEDGER_URL}/register; \
  #       sleep 2; \
  #       aca-py start \
  #       --inbound-transport http '0.0.0.0' 8030 \
  #       --endpoint ${AGENT_ENDPOINT} \
  #       --outbound-transport http \
  #       --genesis-url 'http://dockerhost:9000/genesis' \
  #       --auto-accept-invites \
  #       --auto-accept-requests \
  #       --auto-ping-connection \
  #       --auto-respond-messages \
  #       --auto-respond-credential-proposal \
  #       --auto-respond-credential-offer \
  #       --auto-respond-credential-request \
  #       --auto-verify-presentation \
  #       --wallet-type 'indy' \
  #       --seed 'the_org_book_0000000000000000004' \
  #       --admin '0.0.0.0' 8031 \
  #       --admin-insecure-mode \
  #       --label Alice ",
  #     ]

networks:
  von:

volumes:
  client-cli:
  client-data:
  webserver-cli:
  webserver-ledger:
  node1-data:
  node2-data:
  node3-data:
  node4-data:
  nodes-data:
